[tasks.docs]
clear = true
command = "cargo"
args = ["doc"]

[tasks.build]
dependencies = ["docs"]
clear = true
script = '''
cargo b -Z unstable-options --out-dir isodir/boot/
grub-mkrescue -o arvinos.iso isodir
'''

[tasks.build_release]
dependencies = ["docs"]
clear = true
script = '''
cargo b -r -Z unstable-options --out-dir isodir/boot/
grub-mkrescue -o arvinos.iso isodir
'''

[tasks.run]
dependencies = ["build_release"]
script = '''
qemu-system-x86_64 -m 2048 -drive format=raw,file=arvinos.iso
'''

[tasks.test]
disabled = true
